//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirsrConnectOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public decimal ID { get; set; }
        public decimal CUSTOMER_ID { get; set; }
        public decimal TOTAL { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
