//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirsrConnectOracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.BILLS = new HashSet<BILL>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string CITY { get; set; }
    
        public virtual ICollection<BILL> BILLS { get; set; }
    }
}
